# Stage 1: Build the Vue.js application
FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/shell/package*.json ./
RUN npm install
COPY frontend/shell/. ./
RUN npm run build

# Stage 2: Serve the application using Nginx
FROM nginx:1.21.3-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/shell/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
