# Stage 1: Build the application using Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY user-service/pom.xml ./user-service/
RUN mvn -f user-service/pom.xml dependency:go-offline
COPY user-service/src ./user-service/src
RUN mvn -f user-service/pom.xml package

# Stage 2: Create the final lightweight image
FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/user-service/target/*.jar ./app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
